# Generated by Django 5.0.4 on 2024-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('video_thumbnail', models.ImageField(upload_to='thumbnails')),
                ('videos', models.FileField(upload_to='movies')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
